sudo gem install bundler
sudo gem install jekyll
sudo gem install jekyll-paginate
sudo gem install kramdown
sudo gem install jekyll-gist
sudo gem install rb-pygments
sudo gem install jekyllrb
sudo gem install pygments.rb
sudo gem install jekyll-theme-minimal 
